name: "debug-github-action"

on: workflow_dispatch

jobs:
  debug:
    name: "debug-github-action"
    runs-on: ubuntu-latest
    env:
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      POLICY: "Default IaC policy"
      NAME: ${{ format('{0}-{1}', github.repository, github.ref_name) }}
    steps:
      - name: Output Information
        run: pwd  && env && id && ls -al
      - name: CONCAT
        run: echo "$GITHUB_REPOSITORY/$GITHUB_REF_NAME"
      - name: NAME
        run: echo $NAME
