name: "wiz-dir-scan"

on: workflow_dispatch

jobs:
  wiz-dir-scan:
    name: "Wiz Dir Scan"
    runs-on: ubuntu-latest
    env:
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      SCAN_PATH: "./"
      POLICY: "Default IaC policy"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download Wiz CLI v1.x
        run: curl -o wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli

      - name: Run Wiz CLI dir scan using default policies
        run: |-
          ./wizcli scan dir $SCAN_PATH \
          --name "$GITHUB_REPOSITORY/$GITHUB_REF_NAME" \
          --tags github_action_run_id=${{ github.run_id }} \
          --tags app_id=wiz-code-demo \
          --tags env=dev \
          --tags owner=cnecloud \
          --applications wiz-code-demo
